#                    Copyright (c) 2016-2017
#   Data Intensive Applications and Systems Labaratory (DIAS)
#            Ecole Polytechnique Federale de Lausanne
#
#                      All Rights Reserved.
#
# Permission to use, copy, modify and distribute this software and its
# documentation is hereby granted, provided that both the copyright notice
# and this permission notice appear in all copies of the software, derivative
# works or modified versions, and any portions thereof, and that both notices
# appear in supporting documentation.
#
# This code is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. THE AUTHORS DISCLAIM ANY LIABILITY OF ANY KIND FOR ANY DAMAGES WHATSOEVER RESULTING FROM THE
# USE OF THIS SOFTWARE.

version: '3'

networks:
  net-federation:
    external:
      name: my-network

services:
  exareme-worker:
    image: sofiakar/myexareme:dist
    environment:
      - CONSULURL=exareme-keystore:8500
      - NODE_NAME=${node}
      - DOCKER_DATA_FOLDER=/root/exareme/data/
      - DOCKER_METADATA_FOLDER=/root/exareme/data/
      - EXAREME_ACTIVE_WORKERS_PATH=active_workers
      - EXAREME_MASTER_PATH=master
      - DATASETS=datasets
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == worker       # Ensures starting on worker nodes only
          - node.labels.name == ${node}
    networks:
      - "net-federation"              # Connect the docker container to the global network
    volumes:
      - /home/myWorker/data/:/root/exareme/data/
