before_install:
  - sudo apt-get install -y python-apsw
  - sudo pip install requests NumPy SciPy scikit-learn titus
  
language: java

script: mvn clean install -f Exareme-Docker/src/exareme/pom.xml -DskipTests=false cobertura:cobertura coveralls:report

